project:
  type: website
  render: 
    - "*.md"
    - "*.qmd"

website:
  repo-url: "https://github.com/lsc-hubs/hub-core"
  repo-actions: 
    - edit
    - issue
  page-footer:
    background: dark 
    left: 
    - text: <br/>LSC Hubs 2023
      file: https://www.lsc-hubs.org
  title: "Land Soil Crop Hub"
  navbar:
    background: white
    search: true
    left:
      - text: "Home"
        file: "/hub-core"
      - text: Data
        file: {{< var home >}}#data 
      - text: Maps
        file: {{< var home >}}#maps 
      - text: Use cases
        file: {{< var home >}}#use-cases 
      - text: Community
        file: {{< var home >}}#hub-community 
      - text: "Docs"
        file: {{< var home >}}#documentation  
  sidebar:
    - title: "Docs"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: User
          file: docs/user
        - text: Administrator
          file: docs/admin
        - section: Developer
          contents: 
            - section: Hub components
              contents: docs/developer/*
            - section: Workshop Data
              contents: docs/developer/tutorial-data-management/*

format:
  html:
    theme:
      - cosmo
      - custom.scss
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 300px

      
  






