project:
  type: website
  render: 
    - "*.md"

website:
  page-footer:
    background: dark 
    left: 
    - text: LSC Hubs 2023
      file: https://www.lsc-hubs.org
  title: "LSC Hub"
  navbar:
    background: white
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: Catalogue
        file: "#data"
      - text: Community
        file: "#community" 

format:
  html:
    theme: 
      - cosmo
      - custom.scss
  






