project:
  type: website
  render: 
    - "*.md"
    - "*.qmd"

website:
  page-footer:
    background: dark 
    left: 
    - text: LSC Hubs 2023
      file: https://www.lsc-hubs.org
  title: "Land Soil Crop Hub"
  navbar:
    background: white
    search: true
    left:
      - text: "Home"
        file: "/"
      - text: Catalogue
        file: "/#data"
      - text: Community
        file: "/#hub-community" 
      - text: Docs
        file: "./docs" 
format:
  html:
    theme: 
      - cosmo
      - custom.scss
  






